name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: estevemartin
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push monolith
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:monolith"
          push: true
          tags: "estevemartin/monolith:latest,estevemartin/monolith:${{ github.sha }}"

      - name: Build and push metrics-service
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:metrics-service"
          push: true
          tags: "estevemartin/metrics-service:latest,estevemartin/metrics-service:${{ github.sha }}"
